version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ecommerce_template-nginx
    working_dir: /application
    volumes:
      - ./logs:/application/logs
      - ./docker/nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: mariadb:10.3.3
    container_name: ecommerce_template-db
    working_dir: /application
    env_file:
      - docker/docker-database-prod.env

  php-fpm:
    build: docker/php-fpm
    container_name: ecommerce_template-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
