<?php

namespace common\widgets;

class GridView extends \yii\grid\GridView
{
    public $pjaxId;

    public $options = ['class' => 'table-responsive'];
    public $tableOptions = ['class' => 'table table-striped table-primary table-body-relative mb-2'];
    public $layout = "{items}\n{summary}{pager}";


    public function run()
    {
        if ($this->pjaxId) {
            $view = $this->getView();
            $view->registerJs("
                $(document).on('modal-submitted', function(e, xhr, btn, frm, data) {
                console.log('submitted');
                    if (xhr.success && $('#{$this->pjaxId}').length > 0) { 
                        $.pjax.reload({
                            container:'#{$this->pjaxId}',
                            push: false, 
                            replace: false, 
                            timeout: 10000
                        });
                    }
                });
            ");
        }
        parent::run(); // TODO: Change the autogenerated stub
    }

}