<?php

namespace common\widgets;

use yii\helpers\ArrayHelper;

class TinyMce extends \dosamigos\tinymce\TinyMce
{

    public function run()
    {
        $this->clientOptions = ArrayHelper::merge([
            'class' => ['tinymce-content-container'],
            'menubar' => false,
            'branding' => false,
            'toolbar' => 'undo redo | fontselect | fontsizeselect | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist ',
            'content_style' => 'body { font-family:Arial, Helvetica, sans-serif; font-size:12pt; }'
        ], $this->clientOptions);
        parent::run(); // TODO: Change the autogenerated stub
    }

}