version: "3.8"
services:
  nginx:
    build:
      context: ${ROOT_PATH}
      dockerfile: ./docker/prod/nginx/Dockerfile
    container_name: ecommerce_template-nginx
    working_dir: /application
    volumes:
      - ${ROOT_PATH}/logs:/application/logs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: mariadb:10.3.3
    container_name: ecommerce_template-db
    working_dir: /application
    env_file:
      - ./docker-database.env

  php-fpm:
    build: ./php-fpm
    container_name: ecommerce_template-php-fpm
    working_dir: /application
    volumes:
      - ${ROOT_PATH}:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
