<?php

namespace common\widgets\grid;

use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;

class GridView extends \yii\grid\GridView
{
    public $pjaxId;

    public $tableOptions = ['class' => 'table table-striped table-primary table-body-relative mb-2'];
    public $enableSearch = true;
    public $enableAdd = false;
    public $addButtonOption = [];
    public $collapseToggle;
    public $layout;

    public function init()
    {
        if (!$this->layout) {
            $this->layout = $this->render('_grid_layout');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if ($this->pjaxId) {
            $view = $this->getView();
            $view->registerJs("
                $(document).unbind('modal-submitted').bind('modal-submitted', function(e, xhr, btn, frm, data) {
                    if (xhr.success && $('#{$this->pjaxId}').length > 0) { 
                        $.pjax.reload({
                            container:'#{$this->pjaxId}',
                            push: false, 
                            replace: false, 
                            timeout: 10000,
                        });
                    }
                })
            ");
        }

        $this->layout = Yii::t('app', $this->layout, [
            'collapsable' => $this->collapseToggle,
            'search' => $this->enableSearch ? $this->render('_search') : '',
            'add' => $this->enableAdd ? $this->renderAdd() : ''
        ]);
        parent::run(); // TODO: Change the autogenerated stub
    }

    protected function renderAdd()
    {
        $this->addButtonOption = ArrayHelper::merge([
            'content' => Yii::t('app', 'Add New'),
            'action' => Url::to(['create'])
        ], $this->addButtonOption);

        return Html::tag('span', $this->addButtonOption['content'], [
            'data-href' => $this->addButtonOption['action'],
            'class' => 'btn btn-success btn-modal-control btn-loading my-auto ml-sm-auto mr-0',
        ]);
    }
}