<?php

namespace api\models;

/**
 * Class RegistrationForm
 * @package api\models
 *
 * @property string $password
 * @property string $password_repeat
 *
 */
class RegistrationForm extends User
{
    public $password;
    public $password_repeat;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['email', 'first_name', 'last_name', 'password', 'password_repeat'], 'required'],
            [['address', 'city', 'country', 'zip'], 'string'],
            [['password'], 'compare', 'compareAttribute' => 'password_repeat', 'operator' => '=='],
            [['email'], 'email'],
            [['email', 'username'], 'checkUniqueness']
        ];
    }

    public function beforeValidate()
    {
        $this->username = empty($this->username) ? $this->email : $this->username;
        $this->status = static::STATUS_ACTIVE;

        return parent::beforeValidate();
    }


    public function save($runValidation = true, $attributeNames = null)
    {
        if (!$this->validate()) {
            return false;
        }

        $this->setPassword($this->password);
        $this->generateAuthKey();

        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }
}